name: Observer Notebook Entry
description: Log a lightweight entry to track health, decisions, and patterns.
title: "Observer Entry: {{ date }}"
labels: ["observer", "governance"]
body:
  - type: textarea
    id: signals
    attributes:
      label: Signals
      description: Brief notes on health, risks, or opportunities.
      placeholder: "- ..."
  - type: textarea
    id: decisions
    attributes:
      label: Decisions Reviewed
      description: Link PRs/issues and comment on alignment or tensions.
  - type: textarea
    id: patterns
    attributes:
      label: Emerging Patterns
      description: Any repeating dynamics or shifts noticed.
  - type: input
    id: load
    attributes:
      label: Cognitive Load (1–5)
  - type: textarea
    id: handoff
    attributes:
      label: Handoff Notes / Requests
      description: Optional notes for next steward or observer.

