name: Governance Log Sanity Check

on:
  pull_request:
    paths:
      - 'governance/authority_rotation_log.md'
      - 'governance/authority-rotation-log.md'
      - 'governance/observer-notebook/**'
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  check-governance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate Authority Rotation Log front-matter
        shell: bash
        run: |
          set -euo pipefail
          # Support both hyphenated and underscored filenames during migration
          file=""
          if [ -f governance/authority-rotation-log.md ]; then file="governance/authority-rotation-log.md"; fi
          if [ -z "$file" ] && [ -f governance/authority_rotation_log.md ]; then file="governance/authority_rotation_log.md"; fi
          if [ -z "$file" ]; then echo "❌ Rotation log file not found"; exit 1; fi
          # Require YAML front-matter markers and key fields
          if ! grep -q '^---' "$file"; then
            echo "❌ Missing YAML front-matter block"; exit 1; fi
          required=(date from to mode rationale assessment_date)
          for key in "${required[@]}"; do
            if ! grep -q "^${key}:" "$file"; then
              echo "❌ Missing required field: ${key}"; exit 1; fi
          done
          echo "✅ Rotation log front-matter looks valid"

      - name: Check Observer Notebook activity (7-day nudge)
        shell: bash
        run: |
          set -euo pipefail
          if [ ! -d governance/observer-notebook ]; then
            echo "⚠️ governance/observer-notebook directory not found"; exit 0; fi
          latest=$(find governance/observer-notebook -type f -name '*.md' -printf '%T@ %p\n' | sort -nr | head -1 | awk '{print $2}')
          if [ -z "${latest:-}" ]; then
            echo "⚠️ No observer entries found."; exit 0; fi
          last_ts=$(stat -c %Y "$latest")
          now=$(date +%s)
          diff_days=$(( (now - last_ts) / 86400 ))
          if [ "$diff_days" -gt 7 ]; then
            echo "⚠️ Observer Notebook not updated for ${diff_days} days."; exit 0
          else
            echo "✅ Observer Notebook is current."; exit 0
          fi

      - name: Nudge for missing PR summary
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        run: |
          set -euo pipefail
          body=$(jq -r '.pull_request.body // ""' <(echo '${{ toJson(github.event) }}'))
          missing=false
          if ! grep -qi 'Concise change summary' <<< "$body"; then missing=true; fi
          if ! grep -qi '^[-*]\s*What' <<< "$body"; then missing=true; fi
          if ! grep -qi '^[-*]\s*How' <<< "$body"; then missing=true; fi
          if ! grep -qi '^[-*]\s*Why' <<< "$body"; then missing=true; fi
          if [ "$missing" = true ]; then
            echo "⚠️ Consider adding What / How / Why to the PR body."
          else
            echo "✅ PR contains a concise change summary."
          fi

